import type { EngineSnapshot } from "./types";

const now = Date.now();

export const mockSnapshot: EngineSnapshot = {
  activeSessionId: "session-live",
  model: {
    selected: {
      repoId: "ph0ryn/Qwen3-ASR-1.7B-JA-MLX-8bit",
      revision: "7c70d18cb650655d32eafb952a74a49c6a3caad0",
    },
    status: "ready",
  },
  sessions: [
    {
      characterCount: 238,
      durationMs: 184_000,
      id: "session-live",
      inputKind: "microphone",
      inputName: "MacBookのマイク",
      language: "日本語",
      model: "Qwen3-ASR 1.7B JA",
      rowVersion: 5,
      segmentCount: 3,
      segments: [
        {
          endMs: 21_200,
          id: "live-1",
          language: "Japanese",
          sequence: 1,
          startMs: 2_100,
          text: "本日の打ち合わせでは、文字起こしアプリの完成条件を確認します。",
        },
        {
          endMs: 57_900,
          id: "live-2",
          language: "Japanese",
          sequence: 2,
          startMs: 24_400,
          text: "履歴の検索と書き出しまで、一つの画面から操作できるようにします。",
        },
        {
          endMs: 87_500,
          id: "live-3",
          language: "Japanese",
          sequence: 3,
          startMs: 61_000,
          text: "録音中に過去の記録を開いても、処理はそのまま続きます。",
        },
      ],
      segmentsLoaded: true,
      startedAt: new Date(now - 184_000).toISOString(),
      status: "running",
      title: "新しい録音",
    },
    {
      characterCount: 1_864,
      durationMs: 2_645_000,
      endedAt: new Date(now - 2_400_000).toISOString(),
      id: "session-1",
      inputKind: "file",
      inputName: "プロジェクト定例.wav",
      language: "日本語",
      model: "Qwen3-ASR 1.7B JA",
      rowVersion: 6,
      segmentCount: 4,
      segments: [
        {
          endMs: 13_200,
          id: "s1-1",
          language: "Japanese",
          sequence: 1,
          startMs: 1_100,
          text: "それでは、今週のプロジェクト定例を始めます。",
        },
        {
          endMs: 42_000,
          id: "s1-2",
          language: "Japanese",
          sequence: 2,
          startMs: 15_000,
          text: "先週からの進捗として、音声処理パイプラインの見直しが完了しました。",
        },
        {
          endMs: 76_400,
          id: "s1-3",
          language: "Japanese",
          sequence: 3,
          startMs: 44_000,
          text: "次に、履歴画面の検索性とアクセシビリティを確認します。",
        },
        {
          endMs: 111_900,
          id: "s1-4",
          language: "Japanese",
          sequence: 4,
          startMs: 80_200,
          text: "書き出し形式はテキスト、テキスト (タイムスタンプなし)、Markdown、JSON、字幕に対応します。",
        },
      ],
      segmentsLoaded: true,
      startedAt: new Date(now - 5_045_000).toISOString(),
      status: "completed",
      title: "プロジェクト定例",
    },
    {
      characterCount: 712,
      durationMs: 1_109_000,
      endedAt: new Date(now - 86_000_000).toISOString(),
      id: "session-2",
      inputKind: "microphone",
      inputName: "外部マイク",
      language: "日本語",
      model: "Qwen3-ASR 1.7B JA",
      rowVersion: 4,
      segmentCount: 2,
      segments: [
        {
          endMs: 26_000,
          id: "s2-1",
          language: "Japanese",
          sequence: 1,
          startMs: 2_000,
          text: "ユーザーインタビューの記録です。最初に利用状況を伺いました。",
        },
        {
          endMs: 63_000,
          id: "s2-2",
          language: "Japanese",
          sequence: 2,
          startMs: 29_000,
          text: "検索結果から目的の発言へすぐ移動できることが重要だそうです。",
        },
      ],
      segmentsLoaded: true,
      startedAt: new Date(now - 87_109_000).toISOString(),
      status: "completed",
      title: "ユーザーインタビュー",
    },
    {
      characterCount: 126,
      durationMs: 241_000,
      endedAt: new Date(now - 172_000_000).toISOString(),
      errorCode: "engineCrashed",
      errorMessage: "エンジンが予期せず終了しました。保存済みの部分は残っています。",
      id: "session-3",
      inputKind: "file",
      inputName: "講義録音.m4a",
      language: "日本語",
      model: "Qwen3-ASR 1.7B JA",
      rowVersion: 3,
      segmentCount: 1,
      segments: [
        {
          endMs: 29_000,
          id: "s3-1",
          language: "Japanese",
          sequence: 1,
          startMs: 900,
          text: "保存が完了した部分までを表示しています。",
        },
      ],
      segmentsLoaded: true,
      startedAt: new Date(now - 172_241_000).toISOString(),
      status: "abandoned",
      title: "講義録音 (部分結果)",
    },
  ],
};
